---
# tasks file for certbot---
- name: Ensuring needed pkgs are installed
  yum: 
    name: "{{ certbot_pkgs }}"
    state: installed
  tags:
    - pkgs

- name: Ensuring httpd is installed
  yum: 
    name: httpd 
    state: installed

- name: Ensuring httpd service is started
  service: 
    name: httpd 
    state: started 
    enabled: true

- name: Opening up httpd rule
  include_role:
    name: iptables
    tasks_from: custom-policy
  vars:
    iptables_policy_name: httpd
    iptables_protocol: tcp
    iptables_port: "80"
    iptables_source: "0.0.0.0/0"
  when: httpd_public
  tags:
    - iptables

- name: Installing acme.sh for dns challenge validation
  get_url:
    url: https://raw.githubusercontent.com/Neilpang/acme.sh/master/acme.sh
    dest: /usr/local/bin/acme.sh
    mode: 0755

- name: Default stupid catch-all html index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: 0644

- name: Ensuring backup user and jobs
  include_role:
    name: centos-backup
    tasks_from: client
  vars:
    - centos_role: stikked
    - role_backup_folders:
        - "{{ acme_tls_dir }}"

